// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using enrolmentSystem.Data;

#nullable disable

namespace enrolmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250402162805_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("enrolmentSystem.Models.Admin", b =>
                {
                    b.Property<string>("adminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("adminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Course", b =>
                {
                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Enrolment", b =>
                {
                    b.Property<int>("enrolmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enrolmentID"));

                    b.Property<DateTime?>("enrolDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("paymentID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("enrolmentID");

                    b.HasIndex("paymentID");

                    b.HasIndex("studentID");

                    b.HasIndex("subjectOfferedID")
                        .IsUnique()
                        .HasFilter("[subjectOfferedID] IS NOT NULL");

                    b.ToTable("Enrolments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SubjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectOfferedID");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Inquiry", b =>
                {
                    b.Property<int>("inquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inquiryID"));

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("inquiryID");

                    b.HasIndex("studentID");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Lecturer", b =>
                {
                    b.Property<string>("lecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lecturerID");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Payment", b =>
                {
                    b.Property<int>("paymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentID"));

                    b.Property<int?>("enrolmenttID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Session", b =>
                {
                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<string>("sessionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("sessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
                {
                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HPNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TelNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("alternativeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyHPNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("permanantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semester")
                        .HasColumnType("int");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentID");

                    b.HasIndex("courseID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.Property<string>("subjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("subjectCredit")
                        .HasColumnType("int");

                    b.Property<string>("subjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subjectID");

                    b.HasIndex("courseID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Timetable", b =>
                {
                    b.Property<int>("timetableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("timetableID"));

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("endTime")
                        .HasColumnType("time");

                    b.Property<string>("roomtType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("startTime")
                        .HasColumnType("time");

                    b.Property<int>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("timetableID");

                    b.HasIndex("subjectOfferedID");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("enrolmentSystem.Models.addDropRequest", b =>
                {
                    b.Property<int>("requestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestID"));

                    b.Property<string>("adminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("approvalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("enrolmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("requestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("requestReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("requestID");

                    b.HasIndex("adminID");

                    b.HasIndex("enrolmentID");

                    b.HasIndex("studentID");

                    b.HasIndex("subjectOfferedID");

                    b.ToTable("AddDropRequests");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.Property<int>("subjectOfferedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subjectOfferedID"));

                    b.Property<string>("lecturerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("maxSeats")
                        .HasColumnType("int");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("subjectOfferedID");

                    b.HasIndex("lecturerID");

                    b.HasIndex("sessionID");

                    b.HasIndex("subjectID");

                    b.ToTable("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Enrolment", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Payment", "Payment")
                        .WithMany("Enrolments")
                        .HasForeignKey("paymentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Enrolments")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithOne("Enrolment")
                        .HasForeignKey("enrolmentSystem.Models.Enrolment", "subjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");

                    b.Navigation("Student");

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Evaluation", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Evaluations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithMany("Evaluations")
                        .HasForeignKey("SubjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Inquiry", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Inquiries")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Timetable", b =>
                {
                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithMany("Timetables")
                        .HasForeignKey("subjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.addDropRequest", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Admin", "Admin")
                        .WithMany("AddDropRequests")
                        .HasForeignKey("adminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Enrolment", "Enrolment")
                        .WithMany()
                        .HasForeignKey("enrolmentID");

                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("AddDropRequests")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "subjectOffered")
                        .WithMany()
                        .HasForeignKey("subjectOfferedID");

                    b.Navigation("Admin");

                    b.Navigation("Enrolment");

                    b.Navigation("Student");

                    b.Navigation("subjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Lecturer", "Lecturer")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("lecturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("enrolmentSystem.Models.Session", "Session")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("sessionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Subject", "Subject")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("subjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Session");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Admin", b =>
                {
                    b.Navigation("AddDropRequests");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Lecturer", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Payment", b =>
                {
                    b.Navigation("Enrolments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Session", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
                {
                    b.Navigation("AddDropRequests");

                    b.Navigation("Enrolments");

                    b.Navigation("Evaluations");

                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.Navigation("Enrolment");

                    b.Navigation("Evaluations");

                    b.Navigation("Timetables");
                });
#pragma warning restore 612, 618
        }
    }
}
