// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using enrolmentSystem.Data;

#nullable disable

namespace enrolmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250404111915_courseid")]
    partial class courseid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("enrolmentSystem.Model.Admin", b =>
                {
                    b.Property<string>("adminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("adminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminID");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            adminID = "A001",
                            adminEmail = "cpl@gmail.com",
                            adminName = "Chong Pui Lin",
                            adminPassword = "chongpuilin"
                        },
                        new
                        {
                            adminID = "A002",
                            adminEmail = "cfk@gmail.com",
                            adminName = "Chong Fong Kim",
                            adminPassword = "chongfongkim"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Course", b =>
                {
                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            courseID = "BCSI",
                            courseName = "Bachelor in Computer Science"
                        },
                        new
                        {
                            courseID = "BITI",
                            courseName = "Bachelor in Information Technology"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Student", b =>
                {
                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HPNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TelNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("alternativeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bankAccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("bankHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("currentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("currentPostalCode")
                        .HasColumnType("int");

                    b.Property<string>("currentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyHPNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("permanantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("permanantPostalCode")
                        .HasColumnType("int");

                    b.Property<string>("permanantState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentID");

                    b.HasIndex("courseID");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            studentID = "I22023292",
                            HPNum = "09876543210",
                            TelNum = "01234567890",
                            alternativeEmail = "john.alternate@example.com",
                            bankAccountNumber = 1234567890,
                            bankHolderName = "John Doe",
                            bankName = "ABB: Affin Bank Berhad",
                            courseID = "BCSI",
                            currentAddress = "456 Elm Street",
                            currentArea = "Downtown",
                            currentCountry = "Country",
                            currentPostalCode = 67890,
                            currentState = "State B",
                            emergencyContactName = "James Doe",
                            emergencyContactRelationship = "Father",
                            emergencyHPNum = "01122334455",
                            permanantAddress = "123 Main Street",
                            permanantArea = "City Center",
                            permanantCountry = "Malaysia",
                            permanantPostalCode = 12345,
                            permanantState = "State A",
                            primaryEmail = "johndoe@example.com",
                            studentEmail = "student@example.com",
                            studentName = "John Doe",
                            studentPassword = "hashedpassword123"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Student", b =>
                {
                    b.HasOne("enrolmentSystem.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseID");

                    b.Navigation("Course");
                });
#pragma warning restore 612, 618
        }
    }
}
