// <auto-generated />
<<<<<<< HEAD
using System;
=======
>>>>>>> origin/wy
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using enrolmentSystem.Data;

#nullable disable

namespace enrolmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD
            modelBuilder.Entity("enrolmentSystem.Models.Admin", b =>
=======
            modelBuilder.Entity("enrolmentSystem.Model.Admin", b =>
>>>>>>> origin/wy
                {
                    b.Property<string>("adminID")
                        .HasColumnType("nvarchar(450)");

<<<<<<< HEAD
=======
                    b.Property<string>("adminEmail")
                        .HasColumnType("nvarchar(max)");

>>>>>>> origin/wy
                    b.Property<string>("adminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminID");

<<<<<<< HEAD
                    b.ToTable("Admins");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Course", b =>
=======
                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            adminID = "A001",
                            adminEmail = "cpl@gmail.com",
                            adminName = "Chong Pui Lin",
                            adminPassword = "chongpuilin"
                        },
                        new
                        {
                            adminID = "A002",
                            adminEmail = "cfk@gmail.com",
                            adminName = "Chong Fong Kim",
                            adminPassword = "chongfongkim"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Course", b =>
>>>>>>> origin/wy
                {
                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseName")
<<<<<<< HEAD
                        .IsRequired()
=======
>>>>>>> origin/wy
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("courseID");

<<<<<<< HEAD
                    b.ToTable("Courses");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Enrolment", b =>
                {
                    b.Property<int>("enrolmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enrolmentID"));

                    b.Property<DateTime?>("enrolDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("paymentID")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("enrolmentID");

                    b.HasIndex("paymentID");

                    b.HasIndex("studentID");

                    b.HasIndex("subjectOfferedID")
                        .IsUnique()
                        .HasFilter("[subjectOfferedID] IS NOT NULL");

                    b.ToTable("Enrolments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SubjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectOfferedID");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Inquiry", b =>
                {
                    b.Property<int>("inquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inquiryID"));

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("inquiryID");

                    b.HasIndex("studentID");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Lecturer", b =>
                {
                    b.Property<string>("lecturerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lecturerID");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Payment", b =>
                {
                    b.Property<int>("paymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentID"));

                    b.Property<int?>("enrolmenttID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("paymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("paymentID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Session", b =>
                {
                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<string>("sessionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("sessionID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
=======
                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            courseID = "BCSI",
                            courseName = "Bachelor in Computer Science"
                        },
                        new
                        {
                            courseID = "BITI",
                            courseName = "Bachelor in Information Technology"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Student", b =>
>>>>>>> origin/wy
                {
                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

<<<<<<< HEAD
                    b.Property<string>("CurrentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HPNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TelNum")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");
=======
                    b.Property<string>("HPNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TelNum")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");
>>>>>>> origin/wy

                    b.Property<string>("alternativeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD
                    b.Property<string>("bankDetails")
=======
                    b.Property<int>("bankAccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("bankHolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
>>>>>>> origin/wy
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseID")
                        .HasColumnType("nvarchar(450)");

<<<<<<< HEAD
=======
                    b.Property<string>("currentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("currentPostalCode")
                        .HasColumnType("int");

                    b.Property<string>("currentState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

>>>>>>> origin/wy
                    b.Property<string>("emergencyContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyContactRelationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emergencyHPNum")
                        .IsRequired()
<<<<<<< HEAD
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");
=======
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");
>>>>>>> origin/wy

                    b.Property<string>("permanantAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("permanantArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD
                    b.Property<string>("permanantPostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

=======
                    b.Property<string>("permanantCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("permanantPostalCode")
                        .HasColumnType("int");

>>>>>>> origin/wy
                    b.Property<string>("permanantState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primaryEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD
                    b.Property<int>("semester")
                        .HasColumnType("int");

=======
>>>>>>> origin/wy
                    b.Property<string>("studentEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentID");

                    b.HasIndex("courseID");

<<<<<<< HEAD
                    b.ToTable("Students");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.Property<string>("subjectID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("courseID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("subjectCredit")
                        .HasColumnType("int");

                    b.Property<string>("subjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subjectID");

                    b.HasIndex("courseID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Timetable", b =>
                {
                    b.Property<int>("timetableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("timetableID"));

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("endTime")
                        .HasColumnType("time");

                    b.Property<string>("roomtType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("startTime")
                        .HasColumnType("time");

                    b.Property<int>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("timetableID");

                    b.HasIndex("subjectOfferedID");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("enrolmentSystem.Models.addDropRequest", b =>
                {
                    b.Property<int>("requestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestID"));

                    b.Property<string>("adminID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("approvalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("enrolmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("requestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("requestReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("subjectOfferedID")
                        .HasColumnType("int");

                    b.HasKey("requestID");

                    b.HasIndex("adminID");

                    b.HasIndex("enrolmentID");

                    b.HasIndex("studentID");

                    b.HasIndex("subjectOfferedID");

                    b.ToTable("AddDropRequests");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.Property<int>("subjectOfferedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subjectOfferedID"));

                    b.Property<string>("lecturerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("maxSeats")
                        .HasColumnType("int");

                    b.Property<string>("section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sessionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("subjectID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("subjectOfferedID");

                    b.HasIndex("lecturerID");

                    b.HasIndex("sessionID");

                    b.HasIndex("subjectID");

                    b.ToTable("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Enrolment", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Payment", "Payment")
                        .WithMany("Enrolments")
                        .HasForeignKey("paymentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Enrolments")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithOne("Enrolment")
                        .HasForeignKey("enrolmentSystem.Models.Enrolment", "subjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Payment");

                    b.Navigation("Student");

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Evaluation", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Evaluations")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithMany("Evaluations")
                        .HasForeignKey("SubjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Inquiry", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("Inquiries")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Timetable", b =>
                {
                    b.HasOne("enrolmentSystem.Models.subjectOffered", "SubjectOffered")
                        .WithMany("Timetables")
                        .HasForeignKey("subjectOfferedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.addDropRequest", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Admin", "Admin")
                        .WithMany("AddDropRequests")
                        .HasForeignKey("adminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Enrolment", "Enrolment")
                        .WithMany()
                        .HasForeignKey("enrolmentID");

                    b.HasOne("enrolmentSystem.Models.Student", "Student")
                        .WithMany("AddDropRequests")
                        .HasForeignKey("studentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.subjectOffered", "subjectOffered")
                        .WithMany()
                        .HasForeignKey("subjectOfferedID");

                    b.Navigation("Admin");

                    b.Navigation("Enrolment");

                    b.Navigation("Student");

                    b.Navigation("subjectOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.HasOne("enrolmentSystem.Models.Lecturer", "Lecturer")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("lecturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("enrolmentSystem.Models.Session", "Session")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("sessionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("enrolmentSystem.Models.Subject", "Subject")
                        .WithMany("SubjectsOffered")
                        .HasForeignKey("subjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Session");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Admin", b =>
                {
                    b.Navigation("AddDropRequests");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Lecturer", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Payment", b =>
                {
                    b.Navigation("Enrolments");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Session", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Student", b =>
                {
                    b.Navigation("AddDropRequests");

                    b.Navigation("Enrolments");

                    b.Navigation("Evaluations");

                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("enrolmentSystem.Models.Subject", b =>
                {
                    b.Navigation("SubjectsOffered");
                });

            modelBuilder.Entity("enrolmentSystem.Models.subjectOffered", b =>
                {
                    b.Navigation("Enrolment");

                    b.Navigation("Evaluations");

                    b.Navigation("Timetables");
                });
=======
                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            studentID = "I22023292",
                            HPNum = "+609876543210",
                            TelNum = "+601234567890",
                            alternativeEmail = "john.alternate@example.com",
                            bankAccountNumber = 1234567890,
                            bankHolderName = "John Doe",
                            bankName = "ABB: Affin Bank Berhad",
                            courseID = "BCSI",
                            currentAddress = "456 Elm Street",
                            currentArea = "Downtown",
                            currentCountry = "Malaysia",
                            currentPostalCode = 67890,
                            currentState = "State B",
                            emergencyContactName = "James Doe",
                            emergencyContactRelationship = "Father",
                            emergencyHPNum = "+601122334455",
                            permanantAddress = "123 Main Street",
                            permanantArea = "City Center",
                            permanantCountry = "Malaysia",
                            permanantPostalCode = 12345,
                            permanantState = "State A",
                            primaryEmail = "johndoe@example.com",
                            studentEmail = "student@example.com",
                            studentName = "John Doe",
                            studentPassword = "hashedpassword123"
                        });
                });

            modelBuilder.Entity("enrolmentSystem.Model.Student", b =>
                {
                    b.HasOne("enrolmentSystem.Model.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseID");

                    b.Navigation("Course");
                });
>>>>>>> origin/wy
#pragma warning restore 612, 618
        }
    }
}
